#!/usr/bin/env python3
"""Emit the ONGA -> SO element-type axioms as OWL/Turtle, on stdout.

ONGA terms denote SETS of genomic elements; SO classes denote INDIVIDUAL element
types. The membership relation is carried by `onga:has_element_type`, minted
here, and expressed as a universal restriction on the ONGA class:

    onga:X rdfs:subClassOf [ owl:onProperty onga:has_element_type ;
                             owl:allValuesFrom SO:Y ]

which is an honest, importable statement. The generator NEVER emits a triple
whose subject is an SO IRI -- asserted below. That is the invariant the ADR
"ONGA terms denote sets; SO terms denote elements" exists to protect.

Reads mappings/so.sssom.tsv (hand-curated; the source of truth) BY HEADER
NAME. Rows whose object is sssom:NoTermFound (reviewed, no SO element type)
assert nothing about SO and are skipped. Subject IRIs are rebuilt exactly the
way `gen-owl` builds permissible-value IRIs --
https://databio.org/onga/{EnumName}#{percent-encoded value text} -- so the
axioms merge cleanly with project/owl/onga.owl.ttl. The enum name is re-derived
by looking the subject_label up in src/file_content.yaml (the two enums share no
term names; the lookup errors out if that ever changes).

Usage:
    python scripts/gen_so_axioms.py > project/owl/onga-so-element-types.owl.ttl
"""

import csv
import sys
from pathlib import Path
from urllib.parse import quote

import yaml

ROOT = Path(__file__).resolve().parents[1]
SSSOM = ROOT / "mappings" / "so.sssom.tsv"
SCHEMA = ROOT / "src" / "file_content.yaml"

ONGA_BASE = "https://databio.org/onga/"
SO_BASE = "http://purl.obolibrary.org/obo/SO_"

HAS_ELEMENT_TYPE = "onga:has_element_type"
NO_TERM_FOUND = "sssom:NoTermFound"

PREAMBLE = """@prefix onga: <https://databio.org/onga/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix SO: <http://purl.obolibrary.org/obo/SO_> .

# ONGA -> Sequence Ontology element-type axioms.
# GENERATED by scripts/gen_so_axioms.py from mappings/so.sssom.tsv -- do not edit.
#
# An ONGA DataType or FeatureType term names a SET of genomic elements (a file, a
# track, a set of rows). An SO class names an INDIVIDUAL element type. ONGA never
# asserts identity, equivalence or hierarchy against an SO class, and no triple
# below has an SO IRI as its subject. See the ADR "ONGA terms denote sets; SO
# terms denote elements" and DECISIONS.md design principle #7.

onga:has_element_type a owl:ObjectProperty ;
    rdfs:label "has element type" ;
    rdfs:comment "Relates an ONGA content term, which denotes a SET of genomic elements (a file, a track, a set of rows), to the Sequence Ontology class that its individual members instantiate. An ONGA term is never equivalent to an SO class." .
"""


def so_iri(curie):
    return "<" + SO_BASE + curie.split(":", 1)[1] + ">"


def pv_iri(enum_name, term):
    """The IRI gen-owl mints for a permissible value: base/{Enum}#{quoted text}."""
    return f"<{ONGA_BASE}{enum_name}#{quote(term)}>"


def rows():
    with open(SSSOM) as fh:
        return list(csv.DictReader(
            (line for line in fh if not line.startswith("#")), delimiter="\t"))


def main():
    schema = yaml.safe_load(open(SCHEMA))["enums"]
    enum_of = {}
    for enum_name in ("DataType", "FeatureType"):
        for term in schema[enum_name]["permissible_values"]:
            if term in enum_of:
                sys.exit(f"ERROR: term {term!r} is in both enums; the subject IRI "
                         f"cannot be derived from the label alone. Add an "
                         f"onga_enum column to {SSSOM.name}.")
            enum_of[term] = enum_name

    data = rows()
    if not data:
        sys.exit(f"ERROR: no rows in {SSSOM}")

    # Group membership rows: one restriction per subject, unioned over its
    # element types (a mixed set carries several).
    members, others, order = {}, [], []
    for r in data:
        label = r["subject_label"]
        if label not in enum_of:
            sys.exit(f"ERROR: subject_label {label!r} is in neither enum")
        subj = pv_iri(enum_of[label], label)
        pred = r["predicate_id"]
        obj = r["object_id"]
        if obj == NO_TERM_FOUND:
            continue
        if pred == HAS_ELEMENT_TYPE:
            if subj not in members:
                members[subj] = {"label": label, "so": [], "fit": r.get("element_type_fit", "")}
                order.append(subj)
            if obj not in members[subj]["so"]:
                members[subj]["so"].append(obj)
        else:
            others.append((subj, label, pred, obj))

    out = [PREAMBLE]

    out.append("\n# --- Element-type restrictions (membership: every row of a file bearing\n"
               "# --- the subject term is an instance of the object SO class).\n")
    for subj in order:
        rec = members[subj]
        fit = rec["fit"]
        if len(rec["so"]) == 1:
            filler = so_iri(rec["so"][0])
        else:
            items = " ".join(so_iri(o) for o in rec["so"])
            filler = f"[ owl:unionOf ( {items} ) ]"
        out.append(
            f"# {rec['label']}  (element_type_fit: {fit})\n"
            f"{subj} rdfs:subClassOf [\n"
            f"    a owl:Restriction ;\n"
            f"    owl:onProperty onga:has_element_type ;\n"
            f"    owl:allValuesFrom {filler} ] .\n")

    if others:
        out.append("\n# --- Plain SKOS triples. skos:relatedMatch = the members are NOT\n"
                   "# --- instances. skos:exactMatch / closeMatch appear only for the two\n"
                   "# --- whitelisted SO classes that are themselves set-denoting.\n")
    for subj, label, pred, obj in others:
        out.append(f"# {label}\n{subj} {pred} {so_iri(obj)} .\n")

    ttl = "\n".join(out)

    # THE INVARIANT: no triple in this file may have an SO IRI as its subject.
    for line in ttl.splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or stripped.startswith("@"):
            continue
        if stripped.startswith("<" + SO_BASE) or stripped.startswith("SO:"):
            sys.exit(f"ERROR: generated an SO IRI as a triple subject: {stripped!r}. "
                     f"ONGA must never mutate SO. See the ADR 'ONGA terms denote sets; "
                     f"SO terms denote elements'.")

    sys.stdout.write(ttl)
    print(f"\n# {len(order)} element-type restrictions, {len(others)} SKOS triples, "
          f"0 SO IRIs as subjects.", file=sys.stderr)


if __name__ == "__main__":
    main()
